---
<<<<<<< HEAD
# Create Controller applications
- name: "Managing Controller Applications"
  application:
    name:                           "{{ __application_item.name | mandatory }}"
    new_name:                       "{{ __application_item.new_name | default(omit, true) }}"
    organization:                   "{{ __application_item.organization | mandatory }}"
    description:                    "{{ __application_item.description | default(('' if controller_configuration_applications_enforce_defaults else omit), true) }}"
    authorization_grant_type:       "{{ __application_item.authorization_grant_type | default('password') }}"
    client_type:                    "{{ __application_item.client_type | default('public') }}"
    redirect_uris:                  "{{ __application_item.redirect_uris | default([]) }}"
    skip_authorization:             "{{ __application_item.skip_authorization | default((false if controller_configuration_applications_enforce_defaults else omit), true) }}"
    state:                          "{{ __application_item.state | default(controller_state | default('present')) }}"

    # Role specific options
    controller_username:            "{{ controller_username | default(omit, true) }}"
    controller_password:            "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
    request_timeout:                "{{ controller_request_timeout | default(omit, true) }}"
    controller_host:                "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
    validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ applications if applications is defined else controller_applications }}"
  loop_control:
    loop_var: "__application_item"
    label: "{{ __operation.verb }} Controller Application {{ __application_item.name }}"
    pause: "{{ controller_configuration_applications_loop_delay }}"
  no_log: "{{ controller_configuration_applications_secure_logging }}"
  async: "{{ ansible_check_mode | ternary(0, 1000) }}"
  poll: 0
  register: __applications_job_async
  changed_when: "(__applications_job_async.changed if ansible_check_mode else false)"
  vars:
    __operation: "{{ operation_translate[__application_item.state | default(controller_state) | default('present')] }}"
    ansible_async_dir: '{{ controller_configuration_async_dir }}'

- name: "Flag for errors (check mode only)"
  ansible.builtin.set_fact:
    error_flag: true
  when: ansible_check_mode and __applications_job_async.failed is defined and __applications_job_async.failed

- name: "Managing Controller Applications | Wait for finish the Application management"
  ansible.builtin.async_status:
    jid: "{{ __applications_job_async_results_item.ansible_job_id }}"
  register: __applications_job_async_result
  until: __applications_job_async_result.finished
  retries: "{{ controller_configuration_applications_async_retries }}"
  delay: "{{ controller_configuration_applications_async_delay }}"
  loop: "{{ __applications_job_async.results }}"
  loop_control:
    loop_var: __applications_job_async_results_item
    label: "{{ __operation.verb }} Controller Application {{ __applications_job_async_results_item.__application_item.name }} | Wait for finish the Application {{ __operation.action }}"
  when: not ansible_check_mode and __applications_job_async_results_item.ansible_job_id is defined
  no_log: "{{ controller_configuration_applications_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__applications_job_async_results_item.__application_item.state | default(controller_state) | default('present')] }}"
    ansible_async_dir: '{{ controller_configuration_async_dir }}'
=======
# Create gateway applications
- name: Managing gateway Applications
  ansible.platform.application:
    name: "{{ __application_item.name | mandatory }}"
    new_name: "{{ __application_item.new_name | default(omit, true) }}"
    organization: "{{ __application_item.organization | mandatory }}"
    new_organization: "{{ __application_item.new_organization | default(omit, true) }}"
    description: "{{ __application_item.description | default(('' if applications_enforce_defaults else omit), true) }}"
    authorization_grant_type: "{{ __application_item.authorization_grant_type | default('password') }}"
    client_type: "{{ __application_item.client_type | default('public') }}"
    redirect_uris: "{{ __application_item.redirect_uris | default(omit) }}"
    skip_authorization: "{{ __application_item.skip_authorization | default((false if applications_enforce_defaults else omit), true) }}"
    algorithm: "{{ __application_item.algorithm | default(omit, true) }}"
    post_logout_redirect_uris: "{{ __application_item.post_logout_redirect_uris | default(omit, true) }}"
    user: "{{ __application_item.user | default(omit, true) }}"
    state: "{{ __application_item.state | default(gateway_state | default(omit, true)) }}"

    # Role specific options
    gateway_hostname: "{{ gateway_hostname | default(omit, true) }}"
    gateway_username: "{{ gateway_username | default(omit, true) }}"
    gateway_password: "{{ gateway_password | default(omit, true) }}"
    gateway_token: "{{ gateway_oauthtoken | default(omit, true) }}"
    gateway_request_timeout: "{{ gateway_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ gateway_validate_certs | default(omit) }}"
  loop: "{{ applications if applications is defined else applications_list }}"
  loop_control:
    loop_var: __application_item
  no_log: "{{ applications_secure_logging }}"
  async: "{{ ansible_check_mode | ternary(0, 1000) }}"
  poll: 0
  register: __gateway_applications_job_async
  changed_when: not __gateway_applications_job_async.changed
  vars:
    ansible_async_dir: "{{ platform_configuration_async_dir | default(omit) }}"

- name: Applications | Wait for finish the configuration
  ansible.builtin.async_status:
    jid: "{{ __gateway_applications_job_async_results_item.ansible_job_id }}"
  register: __gateway_applications_job_async_result
  until: __gateway_applications_job_async_result.finished
  retries: "{{ applications_async_retries }}"
  delay: "{{ applications_async_delay }}"
  loop: "{{ __gateway_applications_job_async.results }}"
  loop_control:
    loop_var: __gateway_applications_job_async_results_item
  when: __gateway_applications_job_async_results_item.ansible_job_id is defined
  no_log: "{{ applications_secure_logging }}"
  vars:
    ansible_async_dir: "{{ platform_configuration_async_dir | default(omit) }}"
>>>>>>> 40b40ddac1c00aac7d878bd41af23a6d562296e5
...
